INSERT INTO esthetic.EMPLOYEE (id_person, date_of_hire)
SELECT
    id AS id_person,
    DATE_ADD( -- DATE_ADD REALIZA LA SUMA Y RETORNA LA FECHA
		'2023-07-01',
		INTERVAL FLOOR(  -- INTERVAL ESPECIFICA LA CANTIDAD A SUMAR / RESTAR 
		RAND() *  -- RAND ME GENERA UN NUMERO ALEATORIO ENTRE 0 Y 1 Y CON FLOOR REDONDEO HACIA ABAJO
		DATEDIFF('2023-07-31', '2023-07-01')  -- DATEDIFF ME RETORNA LA DIFERENCIA DE DIAS ENTRE LA FECHA DE INICIO Y LA FECHA DE FIN
		) DAY) AS date_of_hire
FROM esthetic.PERSON
LIMIT 10
OFFSET 10;

INSERT INTO esthetic.EMPLOYEE_SPECIALTY (id_employee, id_specialty)
SELECT
    id AS id_employee,
    (SELECT id FROM esthetic.SPECIALTY ORDER BY RAND() LIMIT 1) AS id_specialty
FROM esthetic.EMPLOYEE;

INSERT INTO esthetic.EMPLOYEE_WORK_SCHEDULE (id_employee, id_work_schedule)
SELECT
    id AS id_employee,
    (SELECT id FROM esthetic.WORK_SCHEDULE) AS id_work_schedule
FROM esthetic.EMPLOYEE;
